/* eslint-disable no-unused-vars */
export enum ActionType {
  SWAL_LOADING = 'SWAL_LOADING',
  USER_LOGIN = 'USER_LOGIN',
  USER_REGISTER = 'USER_REGISTER',
  USER_LOGOUT = 'USER_LOGOUT',
  USER_DATA = 'USER_DATA',
  USER_ROLE = 'USER_ROLE',

  SERVICES_DATA = 'SERVICES_DATA',
  SERVICE_LAUNDRY = 'SERVICE_LAUNDRY',
  SERVICE_REVIEW = 'SERVICE_REVIEW',

  PROMO_LIST = 'PROMO_LIST',
  PROMO_BY_SERVICE = 'PROMO_BY_SERVICE',

  ORDER_LIST = 'ORDER_LIST',

  OPTION_STOCK_LIST = 'OPTION_STOCK_LIST',
  STOCK_LIST = 'STOCK_LIST',
  IN_OUT_STOCK_LIST = 'IN_OUT_STOCK_LIST',
}
